"""add opt

Revision ID: 712867cadabb
Revises: 9fb8ea8c8860
Create Date: 2022-02-19 13:32:56.094516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '712867cadabb'
down_revision = '9fb8ea8c8860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('opt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'opt')
    # ### end Alembic commands ###
