"""auto

Revision ID: 9fb8ea8c8860
Revises: f4b07dfbae7d
Create Date: 2022-02-19 01:18:54.765000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fb8ea8c8860'
down_revision = 'f4b07dfbae7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
